default_provider = "age"

[providers.age]
type = "age"
recipients = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICxGA5zxvbqg162FmdEcTu8TkUKDj3uBqqD7IXsB68kh"]

[secrets]
SESSION= { description = "Advent of Code Session", provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHc4S3kzQSBDb0JUdWRyTkR2UlRtMkJ4YnpiSkRGNTB6RkdCTytnZzFLdFpKUC9nSmhBCnRRT1FmaGU4RUt3RmxlNHRweDdKOExEWjhWbTNEV1pidzh5MzVjUHZiOFUKLT4gdHRTQC1ncmVhc2UgcW42YyBeRQpkMDh2T2V0MW51eHY4T3N0ZUJYR01lZ1Yvek8vWnkzY0xoUStrU2FwYUJCOUlGWUpTSDJyYmo3eUQyQmQra0M5Ck5JYldlQzI5TkNMSzVTc3d4TGF0VGFTeHcrRE9jekg4enFUa2hFdDNtZwotLS0gU1cvZE9yTzVqNWw0b3NMWmZWdjJZdlZBU1pEMUVOR21UeGcwTTFqL1NuMArEugD/KB1HiRovQTMnFptnoRm22MScrO+orcgEqvl22JzzS38GosYOMnDYkMQldOn3K9WAMfkaHGBTrebOnWMKDlAN6nkm/DbSyp3A4RGZKuBM7Ag+Bf4tjyOV0w/wsjR6pO4xCpcrHKt4BsW5leIYs7mTssw/3E+ZaFlrPdsbWCUHQ8sU7q8jcldB7bTBxPi+U6ec6yYG2tqlroeU16o3" }
